services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
